### PR TITLE
markdown support

### PR DESCRIPTION
**Pull request by p0we7**
* The issue in the notice is implemented with line break.
* The notification format adopts markdown.

### CODE REVIEW

**Comment by p0we7** [comment]
> Hi, thanks for the PR. I think in markdown [a proper line break(<br/>) requires two spaces before the \n](https://www.markdownguide.org/basic-syntax/#line-breaks), so wouldn't adding two spaces before the \n be more in line with the markdown specification?
@lyc8503 

I tried using one line break and it runs fine. 

What is the reason for using two line breaks?

image

***
      body: `Service is unavailable since ${timeIncidentStartFormatted} (${downtimeDuration} minutes).<br/>**Issue:** ${reason || "unspecified"}`
***

**Comment by lyc8503** [comment]
> I tried using one line break and it runs fine.
> 
> What is the reason for using two line breaks?

I don't mean that we need two line breaks, I mean that according to the markdown specs, we should put two spaces before the “\n”, [some markdown implementations won't do it if the space is missing](https://github.com/microsoft/vscode/issues/1679). (“line1  \nline2” instead of “line1\nline2”)

Another thing I'm concerned about is that the apprise supports multiple push channels, but if there is a channel that doesn't support markdown, will the send fail or will it be automatically converted to text? I just took a brief look at the apprise code but couldn't find an answer.

**Comment by p0we7** [comment]
I will check if apprise supports converting HTML tags in text mode.

**Comment by lyc8503** [comment]
Thanks, I've been busy lately, I'll test and merge it later.

**Comment by p0we7** [comment]
I tested bark, which supports \n newline characters but doesn't support HTML and markdown. Therefore, I think my current approach is not a good solution.

Generally speaking, apprise sets some additional parameters through URLs, but this involves handling the notification format, where it is necessary to distinguish between text and other formats of the body.

I have another question, does uptimeflare now support setting multiple notification types, that is setting multiple apprise URLs?

**Comment by lyc8503** [comment]
> I have another question, does uptimeflare now support setting multiple notification types, that is setting multiple apprise URLs?

You should be able to separate multiple Apprise URLs with commas to send notifications to multiple targets at the same time.

---

As far as markdown support is concerned, I think text-formatted messages are more than enough to get the message across. Some notification channels may not be able to support markdown well (I've had problems with WeCom only being able to view markdown in WeCom client, and Wechat not being able to display markdown at all, which I find annoying).

So until a more advanced solution is introduced (such as allowing users to customize notification templates), I'm closing this PR for now.

Thanks for your contribution anyway!

**Pull request closed without merging**
